# Generated by Django 5.2.13 on 2026-05-11 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_power_watts',
            field=models.FloatField(default=0.0, help_text='Most recent power reading reported by the device.', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last telemetry packet received from the device.', null=True),
        ),
    ]
