# Generated by Django 5.2.13 on 2026-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_device_last_power_watts_device_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='shed_at',
            field=models.DateTimeField(blank=True, help_text='When the balancing algorithm last shed this device. Cleared on successful auto-restore or on manual ON via the toggle endpoint. Used to enforce the AUTO-mode restore cooldown.', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='restore_cooldown_seconds',
            field=models.PositiveIntegerField(default=30, help_text='In AUTO mode, the minimum number of seconds between when a device was shed and when it may be restored automatically.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='restore_mode',
            field=models.CharField(choices=[('AUTO', 'Auto-restore with cooldown'), ('MANUAL', 'Manual restore only (latching)')], default='AUTO', help_text='AUTO: algorithm re-enables shed devices once load drops (with a cooldown). MANUAL: shed devices stay off until an operator toggles them back on through the UI.', max_length=8),
        ),
    ]
