# Generated by Django 5.2.13 on 2026-05-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_device_shed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='is_on',
            field=models.BooleanField(default=True, help_text='Snapshot of `Device.is_on` at the moment this sample was ingested. '),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='restore_mode',
            field=models.CharField(choices=[('AUTO', 'Auto-restore with cooldown'), ('MANUAL', 'Manual restore only (latching)')], default='AUTO', help_text='AUTO: algorithm re-enables shed devices once load drops (with a cooldown). MANUAL: shed devices stay off until an user toggles them back on through the UI.', max_length=8),
        ),
    ]
