# Generated by Django 5.2.13 on 2026-05-22 23:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_telemetry_is_on_alter_systemsettings_restore_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalancingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SHED', 'Shed (turned off due to overload)'), ('RESTORE', 'Restore (turned back on after slack appeared)')], max_length=8)),
                ('device_power_watts', models.FloatField(help_text='The device draw used by the algorithm when deciding to act.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_power_watts', models.FloatField(help_text='Total system load AFTER this action was applied.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('power_limit_watts', models.PositiveIntegerField(help_text='SystemSettings.power_limit_watts at the time of the event.')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancing_events', to='main.device')),
            ],
            options={
                'verbose_name': 'Balancing event',
                'verbose_name_plural': 'Balancing events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['-occurred_at'], name='main_balanc_occurre_cb510b_idx'), models.Index(fields=['action', '-occurred_at'], name='main_balanc_action_4d6d2b_idx')],
            },
        ),
    ]
