# Generated by Django 5.2.13 on 2026-05-23 06:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_balancingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SHED', 'Auto-shed by balancing algorithm'), ('RESTORE', 'Auto-restored by balancing algorithm'), ('MANUAL_ON', 'Manually switched on by operator'), ('MANUAL_OFF', 'Manually switched off by operator')], max_length=12)),
                ('power_watts', models.FloatField(default=0.0, help_text='Snapshot of last_power_watts at the time of the action.', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main.device')),
            ],
            options={
                'verbose_name': 'Device event',
                'verbose_name_plural': 'Device events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['device', '-occurred_at'], name='main_device_device__513c60_idx'), models.Index(fields=['action', '-occurred_at'], name='main_device_action_bad11e_idx')],
            },
        ),
    ]
