# Generated by Django 5.2.13 on 2026-05-30 16:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_deviceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tariff_uah_per_kwh',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.32'), help_text='Cost of one kilowatt-hour in UAH', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
